### ISSUE TITLE
update pinouts in examples

### ISSUE THREAD

**Issue by jepler** [adafruit/Adafruit_CircuitPython_floppy#7]
The current featherwing revision moved several pins. Check the Arduino library for the new assignment

**Comment by FoamyGuy** [comment]
This was resolved by #9

The pins listed here https://github.com/adafruit/Adafruit_CircuitPython_floppy/blob/main/examples/floppy_simpletest.py#L12-L27 and https://github.com/adafruit/Adafruit_CircuitPython_floppy/blob/main/examples/floppy_vfs.py#L43-L59 do now match the ones from the arduino library: https://github.com/adafruit/Adafruit_Floppy/blob/main/examples/02_mfm_test/02_mfm_test.ino#L4-L16
